### ISSUE TITLE
Problem injecting

### ISSUE THREAD

**Issue by enterv0id** [HatchesPls/GrandTheftAutoV-Cheat#3]
Thank you for sharing this project. I really like it, it's well organized.
I have checked the gamestate, crossmap, and can't figure out what's causing the issue

log console gets until: 
```
[Info] GTAV Cheat Initialization Completed
[Debug] Disabled Controls
```

then an error appears ingame in notifyMap says: **Failed to load Texture** and notifyBottom says: Loading configuration file, one moment please and it's crashing no matter what. What am I missing here?

Edit: Also Textures.ytd is in the right place (gtav dir) I've checked twice.

**Comment by HatchesPls** [comment]
Please confirm you have downloaded the latest release from the **Release page**, or have manually compiled the downloaded source code (tag **v1.4.0.2**).

The crashing is indeed weird. Where do you have GTAV.dll located, it is important that it has privilege to create folders and files (e.g. having it in the root of the system drive for example would not work without running the game elevated. This however should still not result in crashing issues).

**Comment by HatchesPls** [comment]
What version of the game are you using? (e.g. Rockstar Games Launcher, Epic Games or Steam). I don't know this for sure yet but it is possible some data structures are different on those versions.

**Comment by enterv0id** [comment]
Yes I compiled myself. Alo, I'm using RGL version of GTA 1.57. I have commented out this function `Cheat::CheatFunctions::LoadConfig();` you've mentioned for someone else before on another issue. Now, the menu loads, but I still have texture problem. It somehow won't find the Textures.ytd file for some reason. 
GTAV.dll located in the project's Build folder alongside with the 'gtav' folder containing Logs/ and Textures.ytd

**Comment by HatchesPls** [comment]
Alright, that is great to hear. 

Since folders and files are getting created I doubt this is the issue but just to be sure; when injecting the cheat, it is important to not use a method called 'Manual mapping' and the injector must not perform any post injection clean-up; this is because the cheat uses WinAPI functions which rely on the module being known by the OS. In terms of 'anti-cheat' detection, this does not matter in any way.

I am currently working on version 1.5. I will have to push back a deeper look into this issue until that update is finalized and released. A refreshed look in the various filesystem functions is needed regardless, various functions are mixed with WinAPI and STD functions which is unnecessarily.

**Comment by enterv0id** [comment]
You're right! Just tried with Extreme Injector, and it works like a charm. No issues with textures and now it's fully loaded. I've been using Xenos64 before. Can't wait for the 1.5 although I'm just getting into mod coding, I'm already in love it :)

Thank you, and keep up the good work

**Comment by HatchesPls** [comment]
Great to hear that! If you have any other issues, be sure to let me know.
