### ISSUE TITLE
Crash Ever 2 hours 

### ISSUE THREAD

**Issue by DayLight696969** [HatchesPls/GrandTheftAutoV-Cheat#59]
you crash when u play with friends

**Comment by HatchesPls** [comment]
Is this something you can reproduce consistently?

**Comment by DayLight696969** [comment]
yes it does it alot

**Comment by sean24YT** [comment]
same for me. ether private game with friends or just normal. missions will DROP fps like bad and then out of no were crash

**Comment by HatchesPls** [comment]
1. Are you using the latest cheat version (which is NOT the latest main branch commit)? If you compile manually, you must run git checkout on the latest version tag.

2. You said it happens when playing with friends, can you reproduce it when playing solo?

3. Are you doing anything in particular when the crash occurs or does it appear to be random?

**Comment by HatchesPls** [comment]
Closing this for now.
